name: Deploy



on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

#       - uses: actions/setup-node@master
#         with:
#           node-version: '10.x'

       - run: cd $GITHUB_WORKSPACE && ./build_docker_image.sh
#       - run: npm run build